version: '3.6'
services:
  mysql:
    container_name: db_mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=8.0
    environment:
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
      - TZ=UTC
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  web_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python /backend/main.py
    container_name: mysql_web_app
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./web_app:/backend
    ports:
      - '127.0.0.1:8080:8080'